---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobmp-topology
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: gobmp-topology
  template:
    metadata:
      labels:
        app: gobmp-topology
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - broker.jalapeno:9092
          - --mock-database
          - "true"
          image: 192.168.80.240:4000/jalapeno/gobmp-topology:0.0.0
          imagePullPolicy: Always
          name: gobmp-topology
metadata:
  name: gobmp-topology
  namespace: default
