apiVersion: v1
kind: ConfigMap
data:
  gobmp.yaml: |
metadata:
  name: gobmp-config
  namespace: default
---
apiVersion: v1
kind: Service
spec:
  ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: perf
      port: 56767
      protocol: TCP
      targetPort: 56767
  selector:
    app: gobmp
  type: ClusterIP
  externalIPs:
    - 10.1.1.100
metadata:
  name: gobmp
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobmp
  template:
    metadata:
      labels:
        app: gobmp
    spec:
      containers:
        - args:
            - --v
            - "5"
            - --kafka-server
            - "kafka:9092"
          image: docker.io/sbezverk/gobmp:wip_af
          imagePullPolicy: Always
          name: gobmp
          ports:
            - containerPort: 5000
              protocol: TCP
              name: 5000-tcp
            - containerPort: 56767
              protocol: TCP
              name: perf
      volumes:
        - name: config-volume
          configMap:
            name: gobmp-config
metadata:
  name: gobmp
  namespace: default
